project:
  type: website
  #output-dir: docs

website:
  title: "Yonghun's Computational Geo-Blog"
  favicon: ./data/_quarto/favicon/geography-icon.png
  page-footer:
    left: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
  navbar:
    left:
      - text: News
        href: /#category=news
      - text: Code
        href: /#category=Code
      - text: Research
        href: /#category=Research
    right:
      - about.qmd
      - text: "![]( ./data/_quarto/icon/512px-ORCID_iD.svg_.png ){style='position:relative; top:-2px' height=17.5px}"
        href: https://orcid.org/0009-0003-6800-2731
        target: _blank
      - icon: github
        menu:
          - text: My Profile
            href: https://github.com/YONGHUNI
            target: _blank
          - text: Source Code
            href: https://github.com/YONGHUNI/blog
            target: _blank

  comments: 
    giscus: 
      repo: YONGHUNI/blog
format:
  html:
    theme:
      light: cosmo #sketchy
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    
execute:
  freeze: auto

filters:
  - quarto-version.lua

#editor: visual

