project:
  type: website
  #output-dir: docs

website:
  title: "Yonghun's Computational Geo-Blog"
  favicon: /data/_quarto/favicon/geography-icon.png
  page-footer:
    left: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    right: "Made with ❤️ by [YONGHUNI](https://yonghuni.github.io/blog/about/me/)"
  navbar:
    left:
      - text: News
        href: /#category=news
      - text: Code
        href: /#category=Code
      - text: Research
        href: /#category=Research
    right:
      - text: About
        menu:
          - text: Me
            href: ./about/me/index.qmd
          - text: This Blog
            href: ./about/blog/index.qmd
        
      - text:  "{{< ai orcid >}}"
        href: https://orcid.org/0009-0003-6800-2731
        target: _blank
      - icon: github
        menu:
          - text: My Profile
            href: https://github.com/YONGHUNI
            target: _blank
          - text: Source Code
            href: https://github.com/YONGHUNI/blog
            target: _blank

#  comments: 
#    giscus: 
#      repo: YONGHUNI/blog
#      theme:
#        light: light
#        dark: cobalt
format:
  html:
    theme:
      light: cosmo #sketchy
      dark: [cosmo, ./misc/theme-dark.scss]
    css: ./misc/styles.css

# freeze computational output
# (see https://quarto.org/docs/projects/code-execution.html#freeze)
execute:
  freeze: auto

filters:
  - ./misc/quarto-version.lua

#editor: visual

