project:
  type: website
  #output-dir: docs

website:
  title: "Welcome to Yonghun's Geo-Blog"
  navbar:
    left:
      - text: test
        href: /#category=news
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YONGHUNI
        target: _blank
      #- icon: twitter
      #  href: https://twitter.com
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    
execute:
  freeze: auto
  
#editor: visual

