project:
  type: website
  #output-dir: docs

website:
  title: "Yonghun's Computational Geo-Blog"
  favicon: ./data/favicon/geography-icon.png
  navbar:
    left:
      - text: News
        href: /#category=news
      - text: Code
        href: /#category=Code
      - text: Research
        href: /#category=Research
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YONGHUNI
        target: _blank
      #- icon: twitter
      #  href: https://twitter.com
  comments: 
    giscus: 
      repo: YONGHUNI/blog
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    
execute:
  freeze: auto
  
#editor: visual

