on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('pyenv/base/environment.yml') }}
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          #auto-update-conda: true
          #channels: conda-forge
          channel-priority: strict
          environment-file: pyenv/base/environment.yml
          activate-environment: baseline
          #auto-activate-base: false
          use-only-tar-bz2: true
      - run: which python
      - name: Install ubuntu dependencies
        #run: sudo apt install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev
        uses: awalsh128/cache-apt-pkgs-action@latest
        with: 
          packages: libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev libmagick++-dev
          version: 1
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"armyknives"'
          #bypass-cache: never
          #working-directory: "quarto/data/1_swiss_army_knives/"
          cache-version: 2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
