on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install ubuntu dependencies
        #run: sudo apt install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev
        uses: awalsh128/cache-apt-pkgs-action@latest
        with: 
          packages: libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev libmagick++-dev
          version: 1      
      
      - name: Install mamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: pyenv/base/environment.yml
          init-shell: bash
          cache-environment: true
          cache-environment-key: ${{ runner.os }}-mamba-${{ env.CACHE_NUMBER }}-${{ hashFiles('pyenv/base/environment.yml') }}

      - name: activate conda environment
        run: |
          which python

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependency
        uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"armyknives"'
          #bypass-cache: never
          #working-directory: "quarto/data/1_swiss_army_knives/"
          cache-version: 2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
